command_prefix = "!"

desc = "Pwease end my misewy, nyaaa~"

# these cogs require additional setup and may not work right away
blocked_cogs = ["gallery", "msg_writer", "stats", "quotes", "music"]

[mensa]

historyfile = "mensa.csv"

[navigation]

left_emo = "<:rl:953752216949358692>"
right_emo = "<:rr:953752217062637588>"
down_emo = "<:down:956234695526449212>"
up_emo = "<:up:956234695107035137>"

[music]

dl_location = "yt"

[api_tokens]

# cute cat pictures nyaaa~
# catapi = ""

#discord
# discord = ""

[sqlite]

dir = "."

# use postgres as general purpose db, takes precedence over sqlite
# [postgres]
# host = "localhost"
# user = "uwu"
# db = "owo"

# requires working pyspark
# [csv]

# dir = "."

[http]

hostname = "0.0.0.0"
ssl_port = 443
no_ssl_port = 80

# to use SSL, set certfile and (optionally) keyfile as per
# https://docs.python.org/3.8/library/ssl.html#ssl.SSLContext.load_cert_chain
# certfile = "/path/to/cert.pem"
# keyfile = "path/to/key.key"

# ssl: serve over https
# no_ssl: serve over http
# at least one must be true to serve anything
ssl = true
# no_ssl = false

# URL at which the site is available (for communicating with users, but not used internally)
# url = "https://your.site/"
