command_prefix = "$"

desc = "Pwease end my misewy, nyaaa~"

# these cogs require additional setup and may not work right away
blocked_cogs = ["gallery", "msg_writer", "stats", "quotes"]

[navigation]

left_emo = "<:rl:953752216949358692>"
right_emo = "<:rr:953752217062637588>"
down_emo = "<:down:956234695526449212>"
up_emo = "<:up:956234695107035137>"

[bottom]

executable = "bottomify"

[api_tokens]

# cute cat pictures nyaaa~
# catapi = ""

#discord
# discord = ""

[sqlite]

dir = "."

# use postgres as general purpose db, takes precedence over sqlite
# [postgres]
# host = "localhost"
# user = "uwu"
# db = "owo"

[csv]

dir = "."

# use kudu as data lake backend, takes precedence over csv
# [kudu]
# host = ["localhost", "localhost", "localhost"]
# port = [7051, 7151, 7251]
# table_prefix = "uwu"